### ISSUE TITLE
Encoding + Texte korrupt

### ISSUE THREAD

**Issue by cukabeka** [akrys/redaxo-usage_check#14]
Hi, habe nach install in R5.4b1 folgende backend-Seite:
![image](https://user-images.githubusercontent.com/688274/30909058-0baf574a-a380-11e7-8085-e6934b981486.png)

**Comment by akrys** [comment]
Ich habe die neue 5.4.0-beta2 aus dem Installer geladen, den usage_check installiert: alles OK.

<img width="1680" alt="bildschirmfoto 2017-09-29 um 06 54 47" src="https://user-images.githubusercontent.com/6718126/31001334-3946871e-a4e3-11e7-9221-23bc5af3d7ee.png">


Was sein kann: Irgendwo wird die Globale $REX-Variable gesetzt und in $REX['VERSION'] eine 4 hinein geschrieben. Dann lande ich im REX4-Modus, wodurch die Sprachdatei in ISO-8859-1 angelegt wird. Dann dürfte der usage_check aber gar nicht mehr funktionieren, weil überall davon ausgegangen wird, dass es sich um eine REX4-Instanz handelt.

Sorry, aber ohne weitere Anhaltspunkte kann ich das nicht weiter untersuchen. Ich müsste alle Addons untersuchen, ob irgendwo $REX['VERSION']=4; gesetzt wird und schauen, was da noch veranstaltet wird, und den das Verhalten zu umgehen.

**Comment by cukabeka** [comment]
Das mit der $REX-Variable kann ich nicht 100% ausschließen, kann das aber gerade auch nicht so einfach nachschauen.

**Comment by AWqxKAWERbXo** [comment]
ich kann dazu eine Test-Installation zur Verfügung stellen. Wir haben das auch ständig auf unserem Server so. (2 unterschiedliche, einmal netbuild und einmal allinkl)

**Comment by akrys** [comment]
Kürzlich hatte ich mir dazu nochmal Gedanken gemacht: Man kann ja aktuell eh nur aus einer Rex-Instanz ein Addon hochladen und nicht, wie vorher über die Webseite (MyRedaxo). Daher würde das jetzt aus dem laufenden Betrieb passieren und somit schon generierte Sprachdateien von meiner lokalen Installtion (mit möglichen Fehlern) mit hochgeladen. (find ich eher weniger gut, zumal man kurz vor Release eh noch mal alle REX-Versionen kreuz und quer testet)

Daher würde ich als nächsten Schritt direkt einen Sprung auf V2 machen und den REXv4-Support einstellen. Dann brauch ich die Sprachdatei nicht in ISO und UTF vorhalten und je nachdem, in welcher Version ich bin den richtigen Inhalt einsetzen. Heißt, ich falle auch nicht mehr in die Situation, dass ein REXv5 läuft, aber ein REXv4 erkannt wird (wie hier wahrscheinlich der Fall).

Netter Nebeneffekt: Ich kann dann meine komplett veraltete KUbuntu-VM für PHP 5.3 in Rente schicken :-D

**Comment by AWqxKAWERbXo** [comment]
okay, wenn das der ausschlaggebende Grund wäre, dann nur zu :)

**Comment by AWqxKAWERbXo** [comment]
Toll :)
