### ISSUE TITLE
Bug: Bilder: Verwendet und nicht verwendet gleichzeitig

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [akrys/redaxo-usage_check#15]
![image](https://user-images.githubusercontent.com/3855487/36119824-816199de-1041-11e8-9117-cb8f01ec009b.png)

**Comment by akrys** [comment]
Das ist nicht notwendigerweise ein Bug. Es ist ja so, dass ich die Datenbank durchsuche. Da kann ich nur die Stellen durchsuchen, die ich kenne. (Module, Templates, YForm)

Daher rufe ich zur Sicherheit nochmal die Core-Funktion ```rex_mediapool_mediaIsInUse``` auf, bei der über den Extension-Point ```MEDIA_IS_IN_USE``` weitere Prüfungen eingehängt werden können.

Mit der Meldung "Die Datei wird lt. Medienpool verwendet" will ich ausdrücken, dass die Datei u.U. genutzt wird, ich es aber mit meiner Suche in dem Moment nicht nachvollziehen kann.
