### ISSUE TITLE
Addon zu FriendsOfREDAXO

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [akrys/redaxo-usage_check#16]
Hey akrys, möchtest du Addon evtl. auch an @friendsofredaxo unter MIT-Lizenz spenden?

**Comment by akrys** [comment]
Die Übertragung zu FOR hab ich schon länger auf dem Zettel.
Dafür möchte ich aber noch ein paar Punkte anpassen, bevor ich das mache.
