### ISSUE TITLE
PHP 7.2 count()

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [akrys/redaxo-usage_check#17]
```
Warning: count(): Parameter must be an array or an object that implements Countable in /www/htdocs/www/redaxo/src/addons/usage_check/pages/_index.php on line 10
```

hier muss count() für PHP7.2 ersetzt werden oder sichergestellt sein, dass der übergebene Wert zählbar ist.

**Comment by akrys** [comment]
Hab bisher kein PHP7.2 im Einsatz.
Ich schau mir das am WE trotzdem mal an. (Setze das dann auf die Schnelle via Docker auf)

**Comment by akrys** [comment]
Hab den "Fehler" gefunden. Es war eine Klasse, wo ich einen Iterator eingebaut hatte. Es schien immer so, das der ein count darauf funktionieren würde. Anscheinend tut es das doch nicht so gut.

Release 2.1 kommt dann in nächsten Tagen. Hab jetzt gerade keine Lust auf tausende Konflikte zwischen Master und Develop. ;-)
