### ISSUE TITLE
Notice: Undefined index: usagecheck_s_id

### ISSUE THREAD

**Issue by skerbis** [akrys/redaxo-usage_check#18]
> Notice: Undefined index: usagecheck_s_id in redaxo/src/addons/usage_check/akrys/redaxo/addon/UsageCheck/Modules/Pictures.php on line 447

REDAXO 5.7
PHP 7.2.x

**Comment by akrys** [comment]
Oh, da scheint es ein Thema in Redaxo 5.7 zu geben. Muss ich mir bei Gelegenheit mal ansehen.
Hoffe nur, dass es die Funktionalität nicht einschränkt. Das sieht mir nämlich stark nach einer geänderten Datenbank-Struktur aus.

**Comment by akrys** [comment]
Warum auf einmal closed???

**Comment by skerbis** [comment]
@akrys verclickt?

**Comment by akrys** [comment]
@skerbis Wahrscheinlich ist die DSGVO schuld: Seitdem muss man so oft den nicht hervorgehobenen Button klicken, dass man sich nun gerne mal verklickt. 😂🙄🤪
