### ISSUE TITLE
Fehlermeldung unter 5.17.1

### ISSUE THREAD

**Issue by abra100pro** [akrys/redaxo-usage_check#22]
/var/www/vhosts/segelprofis.ch/httpdocs/redaxo/src/core/lib/sql/sql.php

Error while executing statement "SELECT f.*, count(s.id) as count

,0 as usagecheck_metaArtIDs 
,0 as usagecheck_metaCatIDs 
,0 as usagecheck_metaMedIDs 

FROM rex_media f
left join `rex_article_slice` s on (
    s.media1=f.filename
 OR s.media2=f.filename
 OR s.media3=f.filename
 OR s.media4=f.filename
 OR s.media5=f.filename
 OR s.media6=f.filename
 OR s.media7=f.filename
 OR s.media8=f.filename
 OR s.media9=f.filename
 OR s.media10=f.filename
 OR find_in_set(f.filename, s.medialist1)
 OR find_in_set(f.filename, s.medialist2)
 OR find_in_set(f.filename, s.medialist3)
 OR find_in_set(f.filename, s.medialist4)
 OR find_in_set(f.filename, s.medialist5)
 OR find_in_set(f.filename, s.medialist6)
 OR find_in_set(f.filename, s.medialist7)
 OR find_in_set(f.filename, s.medialist8)
 OR find_in_set(f.filename, s.medialist9)
 OR find_in_set(f.filename, s.medialist10)

 OR s.value1 like concat('%',f.filename,'%')
 OR s.value2 like concat('%',f.filename,'%')
 OR s.value3 like concat('%',f.filename,'%')
 OR s.value4 like concat('%',f.filename,'%')
 OR s.value5 like concat('%',f.filename,'%')
 OR s.value6 like concat('%',f.filename,'%')
 OR s.value7 like concat('%',f.filename,'%')
 OR s.value8 like concat('%',f.filename,'%')
 OR s.value9 like concat('%',f.filename,'%')
 OR s.value10 like concat('%',f.filename,'%')
 OR s.value11 like concat('%',f.filename,'%')
 OR s.value12 like concat('%',f.filename,'%')
 OR s.value13 like concat('%',f.filename,'%')
 OR s.value14 like concat('%',f.filename,'%')
 OR s.value15 like concat('%',f.filename,'%')
 OR s.value16 like concat('%',f.filename,'%')
 OR s.value17 like concat('%',f.filename,'%')
 OR s.value18 like concat('%',f.filename,'%')
 OR s.value19 like concat('%',f.filename,'%')
 OR s.value20 like concat('%',f.filename,'%')
)

left join rex_article a on (a.id=s.article_id and a.clang_id=s.clang_id)

where s.id is null group by f.filename, f.id,rex_article_art_meta.id,rex_article_cat_meta.id having  ifnull(usagecheck_metaCatIDs, 0) = 0 and ifnull(usagecheck_metaArtIDs, 0) = 0 and ifnull(usagecheck_metaMedIDs, 0) = 0" using params []! SQLSTATE[42S22]: Column not found: 1054 Unknown column 'rex_article_art_meta.id' in 'group statement'

**Comment by abra100pro** [comment]
Nebenbei: Wenn man den **Report a Redaxo Bug** klickt, dann kommt: 
Whoa there!
Your request URL is too long.

**Comment by akrys** [comment]
Am _Report a Redaxo Bug_ liegt nicht im Bereich von Addons. Daher kann ich da aus dem Addon-Umfeld heraus nicht viel daran machen.

Den SQL kann ich aber anpassen. Einen Fix hab ich auch schon angedacht.
Interessant, dass ich in den Fall noch nicht hinein gerannt bin.

Neue Version kommt entweder Freitag-Abend oder am Sonntag (je nachdem wie ich es schaffe)

**Comment by abra100pro** [comment]
Hi Axel, Danke. Ich wusste, das der Report-Bug zu Redaxo, nicht zu dir gehört; ich weiss nur nicht, wer da für was zuständig ist. Danke fürs Fixen, werde es dann versuchen.
