### ISSUE TITLE
Fehler, wenn alle Module / Templates verwendet werden

### ISSUE THREAD

**Issue by novinet-dsteffen** [akrys/redaxo-usage_check#23]
Wenn es keine ungenutzten Module / Templates gibt ($items leer), dann bringt er einen Fehler mit den Rechten des Users. Bis 3.0 funktioniert es, ab 3.1. nicht mehr

**Comment by akrys** [comment]
Oh, danke. Ich hatte bei der Umsetzung von strengeren Datentypen einfach ein leeres Ergebnis zurück gegeben, wenn die Rechte nicht stimmen. Hab das jetzt auf eine saubere Exception umgestellt.
Doof von mir, dass ich keinen Testcase für das leere Ergebnis hatte.

**Comment by novinet-dsteffen** [comment]
Mach dir keinen Kopf. Wenn du Module und Templates noch nach name sortieren könntest statt nach ID, wäre es zauberhaft. Dann könnte man nämlich die Redaxo-Modulliste abgleichen. Aktuell aktualisiere ich ein Projekt mit über 100 Modulen und da muss ich Modul für Modul prüfen, wo es verwendet wird.
