### ISSUE TITLE
SQL Error beim Aufruf von Tab "Bilder"

### ISSUE THREAD

**Issue by luma-wik** [akrys/redaxo-usage_check#24]
Hallo,

habe mir das Plugin installiert und wollte in der "Usage Check / Übersicht" den Reiter "Bilder" öffnen.

Ich bekomme ein SQL Error:

`Error while executing statement "SELECT f.*, count(s.id) as count

,ifnull(rex_article_art_meta.id,0) as usagecheck_metaArtIDs
,0 as usagecheck_metaCatIDs
,0 as usagecheck_metaMedIDs

FROM rex_media f
left join `rex_article_slice` s on (
s.media1=f.filename
OR s.media2=f.filename
OR s.media3=f.filename
OR s.media4=f.filename
OR s.media5=f.filename
OR s.media6=f.filename
OR s.media7=f.filename
OR s.media8=f.filename
OR s.media9=f.filename
OR s.media10=f.filename
OR find_in_set(f.filename, s.medialist1)
OR find_in_set(f.filename, s.medialist2)
OR find_in_set(f.filename, s.medialist3)
OR find_in_set(f.filename, s.medialist4)
OR find_in_set(f.filename, s.medialist5)
OR find_in_set(f.filename, s.medialist6)
OR find_in_set(f.filename, s.medialist7)
OR find_in_set(f.filename, s.medialist8)
OR find_in_set(f.filename, s.medialist9)
OR find_in_set(f.filename, s.medialist10)

OR s.value1 like concat('%',f.filename,'%')
OR s.value2 like concat('%',f.filename,'%')
OR s.value3 like concat('%',f.filename,'%')
OR s.value4 like concat('%',f.filename,'%')
OR s.value5 like concat('%',f.filename,'%')
OR s.value6 like concat('%',f.filename,'%')
OR s.value7 like concat('%',f.filename,'%')
OR s.value8 like concat('%',f.filename,'%')
OR s.value9 like concat('%',f.filename,'%')
OR s.value10 like concat('%',f.filename,'%')
OR s.value11 like concat('%',f.filename,'%')
OR s.value12 like concat('%',f.filename,'%')
OR s.value13 like concat('%',f.filename,'%')
OR s.value14 like concat('%',f.filename,'%')
OR s.value15 like concat('%',f.filename,'%')
OR s.value16 like concat('%',f.filename,'%')
OR s.value17 like concat('%',f.filename,'%')
OR s.value18 like concat('%',f.filename,'%')
OR s.value19 like concat('%',f.filename,'%')
OR s.value20 like concat('%',f.filename,'%')
)

left join rex_article a on (a.id=s.article_id and a.clang_id=s.clang_id)

LEFT join rex_article as rex_article_art_meta on (rex_article_art_meta.id is not null and (rex_article_art_meta.art_file = f.filename or FIND_IN_SET(f.filename, rex_article_art_meta.art_gallery)))

where s.id is null group by f.filename, f.id ,rex_article_art_meta.id,rex_article_cat_meta.id having ifnull(usagecheck_metaCatIDs, 0) = 0 and ifnull(usagecheck_metaArtIDs, 0) = 0 and ifnull(usagecheck_metaMedIDs, 0) = 0 order by f.title asc, f.filename" using params []! 

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'rex_article_cat_meta.id' in 'group statement'

Datei: redaxo/src/core/lib/sql/sql.php:414
URL: /redaxo/index.php?page=usage_check/picture`

Benutze Redaxo 5.18.0 / PHP 8.3.12 / MariaDB 10.6.19

oder muss ich noch etwas konfigurieren?

**Comment by akrys** [comment]
Konfiguriert werden muss da nichts. Ich habe versucht überall möglichst zu erkennen, was man braucht und was nicht.
In deinem Fall braucht man die Kategorien nicht. Dumm, wenn man die Kategorie-Gruppierung dann trotzdem drin hat. Daraus folgt der Fehler `Column not found: 1054 Unknown column 'rex_article_cat_meta.id' in 'group statement'`

Das habe ich jetzt neu geordnet. Das müsste jetzt mit dem neuen Release funktionieren.
