### ISSUE TITLE
Templates: "Alle Templates anzeigen" wirft Fehler

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [akrys/redaxo-usage_check#8]
```
"ErrorException" thrown in /home/netsh108412/html/mobile-optikerin.de/redaxo/src/addons/usage_check/akrys/redaxo/addon/UsageCheck/RexV5/Modules/Templates.php on line 128
Fatal error: Class 'akrys\redaxo\addon\UsageCheck\RexV5\Modules\rex_structure_perm' not found
```

**Comment by akrys** [comment]
Oh, Danke für den Hinweis.

Ist zum Glück nur ne Kleinigkeit. Ich schaue die Tage noch, ob mir das woanders noch unter gekommen ist.
Spätestens am Wochenende mache ich dann die Beta6 fertig und lade sie hoch, damit im Backend aktualisiert werden kann.

**Comment by AWqxKAWERbXo** [comment]
Klar, gerne :) Ist toll, dass es dieses Addon gibt. Noch sind die R5-Installationen so frisch, dass es nicht zum Tragen kommt bei mir, aber ich weiß, der Tag wird kommen, an dem ich sehr dankbar dafür sein werde ;)
