### ISSUE TITLE
Feature / Cronjob: usage-Flag setzen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [akrys/redaxo-usage_check#9]
Hi! Ich würde mir für `search_it` wünschen, dass dein Addon einen Cronjob bereitstellt, der ein Meta-Info-Feld im Medienpool anlegt (`med_usage`) und dort ein Flag setzt, ob und wo diese Datei aktuell in Verwendung ist.

Die einfachste Umsetzung wäre
* `0` nicht in Verwendung
* `1` in Verwendung

die etwas filigranere Art wäre
* `NULL` nicht in Verwendung
* `rex_article,rex_article_slice_rex_file,rex_yform_tabellenname` kommasepariert als SET 

Damit wäre es bspw. möglich, von der `rex_file` eine `VIEW` zu erstellen, die nur PDFs enthält, die aktuell auch in online-Artikeln in Verwendung ist. Diese wird dann von `search_it` anstelle der echten rex_file-Tabelle indexiert. Siehe: https://github.com/tyrant88/search_it/issues/13

Alternativ / ergänzend müssten bei diversen EP (`update_slice`, etc.) die Flags aktualisiert werden. 
Entweder, 
* indem `search_it` eine Funktion im usage_check-Addon aufruft, oder
* die gleichen EP wie bei search_it berücksichtigt werden.

Wenn du für das Feature zu haben wärst, am besten mit @lus kurzschließen.

**Comment by akrys** [comment]
Wäre auf jeden Fall interessant.

Ich müsste mir mal ansehen, ob ich das als Plugin umsetzen kann. Dann könnte man die Funktion ein- und abstellen, wie man es gerade benötigt. Die Datenbankfelder bräuchte man ja z.B. nur in Verbindung mit `search_it`.

Zusätzlich zum Status würde ich noch einen Timestamp der letzten Aktualisierung speichern. Dann kann man an anderer Stelle erkennen, wie aktuell der Wert in `med_usage` tatsächlich ist.
